import { faker } from "@faker-js/faker/locale/en_GH";

export const departmentsArray = [
  "Marketing",
  "Sales",
  "Operations",
  "Finance and Accounting",
  "Technology",
  "Research and Development",
  "Executive Management",
  "Administration",
  "Engineering",
  "Human Resources",
  "Quality Control",
  "Procurement",
  "Customer Service",
];
const jobTitlesArray = [
  "Marketing Specialist",
  "Marketing Manager",
  "Marketing Director",
  "Graphic Designer",
  "Marketing Research Analyst",
  "Marketing Communications Manager",
  "Marketing Consultant",
  "Product Manager",
  "Public Relations",
  "Social Media Assistant",
  "Brand Manager",
  "SEO Manager",
  "Content Marketing Manager",
  "Copywriter",
  "Media Buyer",
  "Digital Marketing Manager",
  "eCommerce Marketing Specialist",
  "Brand Strategist",
  "Vice President of Marketing",
  "Media Relations Coordinator",
  "Administrative Assistant",
  "Receptionist",
  "Office Manager",
  "Auditing Clerk",
  "Bookkeeper",
  "Account Executive",
  "Branch Manager",
  "Business Manager",
  "Quality Control Coordinator",
  "Administrative Manager",
  "Chief Executive Officer",
  "Business Analyst",
  "Risk Manager",
  "Human Resources",
  "Office Assistant",
  "Secretary",
  "Office Clerk",
  "File Clerk",
  "Account Collector",
  "Administrative Specialist",
  "Executive Assistant",
  "Program Administrator",
  "Program Manager",
  "Administrative Analyst",
  "Data Entry",
  "Computer Scientist",
  "IT Professional",
  "UX Designer & UI Developer",
  "SQL Developer",
  "Web Designer",
  "Web Developer",
  "Help Desk Worker/Desktop Support",
  "Software Engineer",
  "Data Entry",
  "DevOps Engineer",
  "Computer Programmer",
  "Network Administrator",
  "Information Security Analyst",
  "Artificial Intelligence Engineer",
  "Cloud Architect",
  "IT Manager",
  "Technical Specialist",
  "Application Developer",
  "Chief Technology Officer (CTO)",
  "Chief Information Officer (CIO)",
];

const sampleFirstNames = [
  "James",
  "Mary",
  "Robert",
  "Patricia",
  "John",
  "Jennifer",
  "Michael",
  "Linda",
  "David",
  "Elizabeth",
  "William",
  "Barbara",
  "Richard",
  "Susan",
  "Joseph",
  "Jessica",
  "Thomas",
  "Sarah",
  "Charles",
  "Karen",
  "Christopher",
  "Lisa",
  "Daniel",
  "Nancy",
  "Matthew",
  "Betty",
  "Anthony",
  "Margaret",
  "Mark",
  "Sandra",
  "Donald",
  "Ashley",
  "Steven	",
  "Kimberly",
  "Paul	",
  "Emily",
  "Andrew",
  "Donna",
  "Joshua	",
  "Michelle",
  "Kenneth",
  "Carol",
  "Kevin",
  "Amanda",
  "Brian",
  "Dorothy",
  "George",
  "Melissa",
  "Timothy",
  "Deborah",
  "Ronald",
  "Stephanie",
  "Edward",
  "Rebecca",
  "Jason",
  "Sharon",
  "Jeffrey",
  "Laura",
  "Ryan",
  "Cynthia",
  "Jacob",
  "Kathleen",
  "Gary",
  "Amy",
  "Nicholas",
  "Angela",
  "Eric",
  "Shirley",
  "Jonathan",
  "Anna",
  "Stephen",
  "Brenda",
  "Larry",
  "Pamela",
  "Justin",
  "Emma",
  "Scott",
  "Nicole",
  "Brandon",
  "Helen",
  "Benjamin",
  "Samantha",
  "Samuel",
  "Katherine",
  "Gregory",
  "Christine",
  "Alexander",
  "Debra",
  "Frank",
  "Rachel",
  "Patrick",
  "Carolyn",
  "Raymond",
  "Janet",
  "Jack",
  "Catherine",
  "Dennis",
  "	Maria",
  "Jerry",
  "	Heather",
  "Tyler",
  "	Diane",
  "Aaron",
  "	Ruth",
  "Jose",
  "	Julie",
  "Adam",
  "	Olivia",
  "Nathan",
  "	Joyce",
  "Henry",
  "	Virginia",
  "Douglas",
  "Victoria",
  "Zachary",
  "Kelly",
  "Peter",
  "Lauren",
  "Kyle",
  "Christina",
  "Ethan",
  "Joan",
  "Walter",
  "Evelyn",
  "Noah",
  "Judith",
  "Jeremy  ",
  "Megan",
  "Christian",
  "Andrea",
  "Keith",
  "Cheryl",
  "Roger",
  "Hannah",
  "Terry",
  "Jacqueline",
  "Gerald",
  "Martha",
  "Harold",
  "Gloria",
  "Sean",
  "Teresa",
  "Austin",
  "Ann",
  "Carl",
  "Sara",
  "Arthur",
  "Madison",
  "Lawrence",
  "Frances",
  "Dylan",
  "Kathryn",
  "Jesse",
  "Janice",
  "Jordan",
  "Jean",
  "Bryan",
  "Abigail",
  "Billy",
  "Alice",
  "Joe",
  "Julia",
  "Bruce",
  "Judy",
  "Gabriel",
  "Sophia",
  "Logan",
  "Grace",
  "Albert",
  "Denise",
  "Willie",
  "Amber",
  "Alan",
  "Doris",
  "Juan",
  "Marilyn",
  "Wayne",
  "Danielle",
  "Elijah",
  "Beverly",
  "Randy",
  "Isabella",
  "Roy",
  "Theresa",
  "Vincent",
  "Diana",
  "Ralph",
  "Natalie",
  "Eugene",
  "Brittany",
  "Russell",
  "Charlotte",
  "Bobby",
  "Marie",
  "Mason",
  "Kayla",
  "Philip",
  "Alexis",
  "Louis",
  "Lori",
];
const genderArray = ["male", "female"];
const maritalStatusArray = ["single", "married"];

const arr = sampleFirstNames.map((e) => e.trim())
function createRandomEmployee() {
  const employee = {
    // first_name: faker.helpers.arrayElement(arr),
    first_name: faker.fake('{{name.firstName}}'),
    last_name: faker.name.lastName(),
    job_title: faker.helpers.arrayElement(jobTitlesArray),
    address: faker.address.streetAddress(true),
    photo: faker.image.avatar(),
    date_of_birth: faker.date.birthdate({ min: 18, max: 60, mode: "age" }),
    phone_number: faker.phone.number("+233 ## ### ####"),
    email: faker.fake('{{name.lastName}}@gmail.com'),
    // email: faker.internet.email(),
    gender: faker.helpers.arrayElement(genderArray),
    nationality: "Ghanaian",
    marital_status: faker.helpers.arrayElement(maritalStatusArray),
    date_of_hire: faker.date.past(),
  };
  return employee;
}

function createDepartment() {
  const department = {
    name: faker.helpers.arrayElement(departmentsArray),
  };
  return department;
}

export { createDepartment, createRandomEmployee };
